language: node_js
node_js:
  - "stable"
env:
  global:
  - export NODE_ENV=test
sudo: false
dist: trusty
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'CREATE DATABASE ridemyway;' -U postgres
  - psql -c "CREATE USER daniel WITH PASSWORD 'password';" -U postgres
script:
  - npm test
after_success: 
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls